name: Build Navidrome for FreeBSD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-freebsd:
    runs-on: freebsd-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 解决本地 Action 依赖问题 - 跳过不需要的步骤
      - name: Install dependencies
        run: |
          sudo pkg update -f
          sudo pkg install -y go ffmpeg make taglib taglib-devel
          # 安装其他可能需要的依赖
          sudo pkg install -y gcc g++

      - name: Check Go version
        run: go version

      # 手动处理 taglib 依赖（替代缺失的 download-taglib Action）
      - name: Prepare taglib
        run: |
          # 如果需要特定版本的 taglib，可以在这里手动下载编译
          echo "Using system-installed taglib"

      - name: Build Navidrome
        run: |
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$PATH
          # 跳过翻译验证步骤，或根据需要调整
          make build-freebsd SKIP_TRANSLATION_CHECK=true

      - name: Verify build output
        run: |
          if [ -f "navidrome" ]; then
            echo "Build successful! Executable file exists."
            file navidrome
          else
            echo "Build failed! Executable file not found."
            exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: navidrome-freebsd
          path: navidrome
